const commonButtonTokens = {
  "component-button-font-size-xs": "0.75rem",
  "component-button-font-size-s": "0.8125rem",
  "component-button-font-size-m": "0.9375rem",
  "component-button-font-size-l": "1.125rem",
  "component-button-height-xs": "1.8125rem",
  "component-button-height-s": "2rem",
  "component-button-height-m": "2.25rem",
  "component-button-height-l": "2.625rem",
  "component-button-radius": "1.125rem",
  "component-button-radius-lg": "1.5rem",
};

export const BUTTON_TOKENS = {
  ...commonButtonTokens,
  "component-button-primary-bg": "var(--color-action-primary)",
  "component-button-primary-border": "var(--color-action-primary)",
  "component-button-primary-text": "var(--color-action-secondary)",
  "component-button-primary-bg-hover": "var(--color-action-primary-hover)",
  "component-button-primary-border-hover": "var(--color-action-primary-hover)",
  "component-button-primary-text-hover": "var(--color-action-secondary)",
  "component-button-primary-bg-pressed": "var(--color-action-secondary)",
  "component-button-primary-border-pressed": "var(--color-action-secondary)",
  "component-button-primary-text-pressed": "var(--color-text-on-brand)",
  "component-button-secondary-bg": "var(--color-bg-surface-strong)",
  "component-button-secondary-border": "var(--color-border-default)",
  "component-button-secondary-text": "var(--color-text-primary)",
  "component-button-secondary-bg-hover": "var(--color-neutral-300)",
  "component-button-secondary-border-hover": "var(--color-border-strong)",
  "component-button-secondary-text-hover": "var(--color-text-primary)",
  "component-button-secondary-bg-pressed": "var(--color-action-primary)",
  "component-button-secondary-border-pressed": "var(--color-action-primary)",
  "component-button-secondary-text-pressed": "var(--color-action-secondary)",
  "component-button-outline-bg": "var(--color-bg-surface)",
  "component-button-outline-border": "var(--color-border-default)",
  "component-button-outline-text": "var(--color-text-primary)",
  "component-button-outline-bg-hover": "var(--color-bg-surface-subtle)",
  "component-button-outline-border-hover": "var(--color-border-strong)",
  "component-button-outline-text-hover": "var(--color-text-primary)",
  "component-button-outline-bg-pressed": "var(--color-bg-surface-strong)",
  "component-button-outline-border-pressed": "var(--color-action-primary)",
  "component-button-outline-text-pressed":
    "var(--color-action-primary-pressed)",
  "component-button-pseudo-bg": "var(--color-bg-canvas)",
  "component-button-pseudo-border": "var(--color-bg-canvas)",
  "component-button-pseudo-text": "var(--color-text-primary)",
  "component-button-pseudo-bg-hover": "var(--color-bg-surface-subtle)",
  "component-button-pseudo-border-hover": "var(--color-bg-surface-subtle)",
  "component-button-pseudo-text-hover": "var(--color-text-primary)",
  "component-button-pseudo-bg-pressed": "var(--color-bg-surface-strong)",
  "component-button-pseudo-border-pressed": "var(--color-bg-surface-strong)",
  "component-button-pseudo-text-pressed": "var(--color-text-primary)",
  "component-button-clear-bg": "transparent",
  "component-button-clear-border": "transparent",
  "component-button-clear-text": "var(--color-text-primary)",
  "component-button-clear-bg-hover": "transparent",
  "component-button-clear-border-hover": "transparent",
  "component-button-clear-text-hover": "var(--color-action-clear-text-hover)",
  "component-button-clear-bg-pressed": "transparent",
  "component-button-clear-border-pressed": "transparent",
  "component-button-clear-text-pressed": "var(--color-action-primary-pressed)",
  "component-button-alert-bg": "var(--color-status-error)",
  "component-button-alert-border": "var(--color-status-error)",
  "component-button-alert-text": "var(--color-brand-white)",
  "component-button-alert-bg-hover": "var(--color-status-error-hover)",
  "component-button-alert-border-hover": "var(--color-status-error-hover)",
  "component-button-alert-text-hover": "var(--color-brand-white)",
  "component-button-alert-bg-pressed": "var(--color-status-error-accent)",
  "component-button-alert-border-pressed": "var(--color-status-error-accent)",
  "component-button-alert-text-pressed": "var(--color-brand-white)",
  "component-button-success-bg": "var(--color-status-success-bg)",
  "component-button-success-border": "var(--color-status-success-bg)",
  "component-button-success-text": "var(--color-text-primary)",
  "component-button-success-bg-hover": "var(--color-status-success-bg-hover)",
  "component-button-success-border-hover":
    "var(--color-status-success-bg-hover)",
  "component-button-success-text-hover": "var(--color-text-primary)",
  "component-button-success-bg-pressed": "var(--color-status-success)",
  "component-button-success-border-pressed": "var(--color-status-success)",
  "component-button-success-text-pressed": "var(--color-brand-white)",
  "component-button-bg-disabled": "var(--color-action-disabled)",
  "component-button-border-disabled": "var(--color-action-disabled)",
  "component-button-text-disabled": "var(--color-action-disabled-text)",
} as const;
