import Color from "../colors";

export default {
  "palette-black": Color.BLACK,
  "palette-white": Color.WHITE,
  "palette-bg-1": Color.BG_1,
  "palette-bg-2": Color.BG_2,
  "palette-bg-3": Color.BG_3,
  "palette-bg-4": Color.BG_4,
  "palette-bg-5": Color.BG_5,
  "palette-brand-default-1": Color.BRAND_BA_1,
  "palette-brand-default-2": Color.BRAND_BA_2,
  "palette-brand-default-3": Color.BRAND_BA_3,
  "palette-primary-1": Color.PRIMARY_BA_1,
  "palette-primary-2": Color.PRIMARY_BA_2,
  "palette-primary-3": Color.PRIMARY_BA_3,
  "palette-primary-4": Color.PRIMARY_BA_4,
  "palette-primary-5": Color.PRIMARY_BA_5,
  "palette-tretiary-1": Color.TRETIARY_BA_1,
  "palette-tretiary-2": Color.TRETIARY_BA_2,
  "palette-tretiary-3": Color.TRETIARY_BA_3,
  "palette-tretiary-4": Color.TRETIARY_BA_4,
  "palette-tretiary-5": Color.TRETIARY_BA_5,
  "palette-alert": Color.ALERT,
};
