import Color from "../colors";

export default {
  "palette-black": Color.BLACK,
  "palette-white": Color.WHITE,
  "palette-bg-1": Color.BG_1,
  "palette-bg-2": Color.BG_2,
  "palette-bg-3": Color.BG_3,
  "palette-bg-4": Color.BG_4,
  "palette-bg-5": Color.BG_5,
  "palette-brand-default-1": Color.BRAND_BA_1,
  "palette-brand-default-2": Color.BRAND_BA_2,
  "palette-brand-default-3": Color.BRAND_BA_3,
  "palette-primary-1": Color.PRIMARY_BA_1,
  "palette-primary-2": Color.PRIMARY_BA_2,
  "palette-primary-3": Color.PRIMARY_BA_3,
  "palette-primary-4": Color.PRIMARY_BA_4,
  "palette-primary-5": Color.PRIMARY_BA_5,
  "palette-tretiary-1": Color.TRETIARY_BA_1,
  "palette-tretiary-2": Color.TRETIARY_BA_2,
  "palette-tretiary-3": Color.TRETIARY_BA_3,
  "palette-tretiary-4": Color.TRETIARY_BA_4,
  "palette-tretiary-5": Color.TRETIARY_BA_5,
  "palette-alert": Color.ALERT,

  "button-border-radius": "18px",
  "button-primary-color": Color.BLACK,
  "button-primary-background-color": Color.PRIMARY_BA_4,
  "button-primary-border-color": Color.PRIMARY_BA_4,
  "button-primary-color-hovered": Color.BLACK,
  "button-primary-background-color-hovered": Color.PRIMARY_BA_4,
  "button-primary-border-color-hovered": Color.PRIMARY_BA_4,
  "button-primary-color-active": Color.BLACK,
  "button-primary-background-color-active": Color.PRIMARY_BA_5,
  "button-primary-border-color-active": Color.PRIMARY_BA_5,
  "button-primary-color-disabled": Color.BG_4,
  "button-primary-background-color-disabled": Color.PRIMARY_BA_1,
  "button-primary-border-color-disabled": Color.PRIMARY_BA_1,

  "button-secondary-color": Color.WHITE,
  "button-secondary-background-color": Color.SECONDARY_BA_4,
  "button-secondary-border-color": Color.SECONDARY_BA_4,
  "button-secondary-color-hovered": Color.WHITE,
  "button-secondary-background-color-hovered": Color.SECONDARY_BA_4,
  "button-secondary-border-color-hovered": Color.SECONDARY_BA_4,
  "button-secondary-color-active": Color.WHITE,
  "button-secondary-background-color-active": Color.SECONDARY_BA_5,
  "button-secondary-border-color-active": Color.SECONDARY_BA_5,
  "button-secondary-color-disabled": Color.BG_4,
  "button-secondary-background-color-disabled": Color.BG_1,
  "button-secondary-border-color-disabled": Color.BG_1,

  "button-outline-color": Color.BLACK,
  "button-outline-background-color": Color.WHITE,
  "button-outline-border-color": Color.SECONDARY_BA_4,
  "button-outline-color-hovered": Color.BLACK,
  "button-outline-background-color-hovered": Color.BG_1,
  "button-outline-border-color-hovered": Color.SECONDARY_BA_4,
  "button-outline-color-active": Color.BLACK,
  "button-outline-background-color-active": Color.BG_2,
  "button-outline-border-color-active": Color.SECONDARY_BA_4,
  "button-outline-color-disabled": Color.BG_4,
  "button-outline-background-color-disabled": Color.WHITE,
  "button-outline-border-color-disabled": Color.BG_2,

  "button-pseudo-color": Color.BLACK,
  "button-pseudo-background-color": Color.TRETIARY_BA_1,
  "button-pseudo-border-color": Color.TRETIARY_BA_1,
  "button-pseudo-color-hovered": Color.BLACK,
  "button-pseudo-background-color-hovered": Color.TRETIARY_BA_1,
  "button-pseudo-border-color-hovered": Color.TRETIARY_BA_1,
  "button-pseudo-color-active": Color.BLACK,
  "button-pseudo-background-color-active": Color.TRETIARY_BA_2,
  "button-pseudo-border-color-active": Color.TRETIARY_BA_2,
  "button-pseudo-color-disabled": Color.BG_4,
  "button-pseudo-background-color-disabled": Color.TRETIARY_BA_1,
  "button-pseudo-border-color-disabled": Color.TRETIARY_BA_1,

  "button-clear-color": Color.SECONDARY_BA_4,
  "button-clear-color-hovered": Color.SECONDARY_BA_4,
  "button-clear-color-active": Color.SECONDARY_BA_5,
  "button-clear-color-disabled": Color.BG_4,
  "button-clear-background-color-disabled": Color.WHITE,
  "button-clear-border-color-disabled": Color.WHITE,

  "input-primary-border-color": Color.BG_3,
  "input-primary-plaseholder-color": Color.BG_2,
  "input-primary-border-color-error": Color.ALERT,
  "input-primary-background-color-error": Color.TRETIARY_DEFAULT_2,
  "input-primary-box-shadow-color-error": Color.TRETIARY_DEFAULT_2,

  "checkbox-background-color-checked": Color.PRIMARY_BA_4,
  "checkbox-background-color-hovered": Color.PRIMARY_BA_4,
  "checkbox-box-shadow-focused": Color.PRIMARY_BA_1,
  "checkbox-background-color-active": Color.PRIMARY_BA_4,
  "checkbox-border-color-active": Color.PRIMARY_BA_4,
  "checkbox-box-shadow-active": Color.PRIMARY_BA_4,
  "checkbox-background-color-disabled": Color.PRIMARY_BA_1,

  "input-radio-background-color-checked": Color.PRIMARY_BA_4,
  "input-radio-background-color-hovered": Color.PRIMARY_BA_4,
  "input-radio-box-shadow-focused": Color.PRIMARY_BA_1,
  "input-radio-background-color-focused": Color.PRIMARY_BA_1,
  "input-radio-border-color-focused": Color.PRIMARY_BA_1,

  "switch-background-color": Color.BG_2,
  "switch-border-color": Color.BG_2,
  "switch-background-color-checked": Color.PRIMARY_BA_5,
  "switch-border-color-checked": Color.PRIMARY_BA_5,

  "tooltip-background-color": Color.SECONDARY_BA_3,
  "tooltip-color": Color.WHITE,
  "tooltip-border-radius": "4px",
};
