import Color from "../colors";

export default {
  "palette-black": Color.BLACK,
  "palette-white": Color.WHITE,
  "palette-bg-1": Color.BG_1,
  "palette-bg-2": Color.BG_2,
  "palette-bg-3": Color.BG_3,
  "palette-bg-4": Color.BG_4,
  "palette-bg-5": Color.BG_5,
  "palette-brand-default-1": Color.BRAND_BA_1,
  "palette-brand-default-2": Color.BRAND_BA_2,
  "palette-brand-default-3": Color.BRAND_BA_3,
  "palette-primary-1": Color.PRIMARY_BA_1,
  "palette-primary-2": Color.PRIMARY_BA_2,
  "palette-primary-3": Color.PRIMARY_BA_3,
  "palette-primary-4": Color.PRIMARY_BA_4,
  "palette-primary-5": Color.PRIMARY_BA_5,
  "palette-secondary-1": Color.SECONDARY_BA_1,
  "palette-secondary-2": Color.SECONDARY_BA_2,
  "palette-secondary-3": Color.SECONDARY_BA_3,
  "palette-secondary-4": Color.SECONDARY_BA_4,
  "palette-secondary-5": Color.SECONDARY_BA_5,
  "palette-tretiary-1": Color.TRETIARY_BA_1,
  "palette-tretiary-2": Color.TRETIARY_BA_2,
  "palette-tretiary-3": Color.TRETIARY_BA_3,
  "palette-tretiary-4": Color.TRETIARY_BA_4,
  "palette-tretiary-5": Color.TRETIARY_BA_5,
  "palette-alert": Color.ALERT,
  "palette-success": Color.SUCCESS,

  "typography-alert": Color.ALERT,
  "typography-success": Color.SUCCESS,
  "typography-secondary": "rgba(0, 0, 0, .6)",

  "button-primary-color": Color.BLACK,
  "button-primary-bg": Color.PRIMARY_BA_4,
  "button-primary-border-color": Color.PRIMARY_BA_4,
  "button-primary-color-hovered": Color.BLACK,
  "button-primary-bg-hovered": Color.PRIMARY_BA_4,
  "button-primary-border-color-hovered": Color.PRIMARY_BA_4,
  "button-primary-color-active": Color.BLACK,
  "button-primary-bg-active": Color.PRIMARY_BA_5,
  "button-primary-border-color-active": Color.PRIMARY_BA_5,
  "button-primary-color-disabled": Color.BG_4,
  "button-primary-bg-disabled": Color.PRIMARY_BA_1,
  "button-primary-border-color-disabled": Color.PRIMARY_BA_1,

  "button-secondary-color": Color.WHITE,
  "button-secondary-bg": Color.SECONDARY_BA_4,
  "button-secondary-border-color": Color.SECONDARY_BA_4,
  "button-secondary-color-hovered": Color.WHITE,
  "button-secondary-bg-hovered": Color.SECONDARY_BA_5,
  "button-secondary-border-color-hovered": Color.SECONDARY_BA_4,
  "button-secondary-color-active": Color.WHITE,
  "button-secondary-bg-active": Color.BLACK,
  "button-secondary-border-color-active": Color.SECONDARY_BA_5,
  "button-secondary-color-disabled": Color.BG_4,
  "button-secondary-bg-disabled": Color.BG_1,
  "button-secondary-border-color-disabled": Color.BG_1,

  "button-outline-color": Color.BLACK,
  "button-outline-bg": Color.WHITE,
  "button-outline-border-color": Color.SECONDARY_BA_4,
  "button-outline-color-hovered": Color.BLACK,
  "button-outline-bg-hovered": Color.BG_1,
  "button-outline-border-color-hovered": Color.SECONDARY_BA_4,
  "button-outline-color-active": Color.BLACK,
  "button-outline-bg-active": Color.BG_2,
  "button-outline-border-color-active": Color.SECONDARY_BA_4,
  "button-outline-color-disabled": Color.BG_4,
  "button-outline-bg-disabled": Color.WHITE,
  "button-outline-border-color-disabled": Color.BG_2,

  "button-pseudo-color": Color.BLACK,
  "button-pseudo-bg": Color.TRETIARY_BA_1,
  "button-pseudo-border-color": Color.TRETIARY_BA_1,
  "button-pseudo-color-hovered": Color.BLACK,
  "button-pseudo-bg-hovered": Color.TRETIARY_BA_1,
  "button-pseudo-border-color-hovered": Color.TRETIARY_BA_1,
  "button-pseudo-color-active": Color.BLACK,
  "button-pseudo-bg-active": Color.TRETIARY_BA_2,
  "button-pseudo-border-color-active": Color.TRETIARY_BA_2,
  "button-pseudo-color-disabled": Color.BG_4,
  "button-pseudo-bg-disabled": Color.TRETIARY_BA_1,
  "button-pseudo-border-color-disabled": Color.TRETIARY_BA_1,

  "button-alert-color": Color.WHITE,
  "button-alert-bg": Color.ALERT,
  "button-alert-border-color": Color.ALERT,
  "button-alert-color-hovered": Color.WHITE,
  "button-alert-bg-hovered": Color.ALERT_HOVER,
  "button-alert-border-color-hovered": Color.ALERT_HOVER,
  "button-alert-color-active": Color.WHITE,
  "button-alert-bg-active": Color.ALERT_ACTIVE,
  "button-alert-border-color-active": Color.ALERT_ACTIVE,
  "button-alert-color-disabled": Color.BG_4,
  "button-alert-bg-disabled": Color.ALERT_LIGHT,
  "button-alert-border-color-disabled": Color.ALERT_LIGHT,

  "button-success-color": Color.BLACK,
  "button-success-bg": Color.SUCCESS,
  "button-success-border-color": Color.SUCCESS,
  "button-success-color-hovered": Color.BLACK,
  "button-success-bg-hovered": Color.SUCCESS_HOVER,
  "button-success-border-color-hovered": Color.SUCCESS_HOVER,
  "button-success-color-active": Color.BLACK,
  "button-success-bg-active": Color.SUCCESS_ACTIVE,
  "button-success-border-color-active": Color.SUCCESS_ACTIVE,
  "button-success-color-disabled": Color.BG_4,
  "button-success-bg-disabled": Color.SUCCESS_LIGHT,
  "button-success-border-color-disabled": Color.SUCCESS_LIGHT,

  "button-clear-color": Color.SECONDARY_BA_4,
  "button-clear-color-hovered": Color.SECONDARY_BA_4,
  "button-clear-color-active": Color.SECONDARY_BA_5,
  "button-clear-color-disabled": Color.BG_4,
  "button-clear-bg-disabled": Color.WHITE,
  "button-clear-border-color-disabled": Color.WHITE,

  "input-primary-border-color": Color.BG_3,
  "input-primary-plaseholder-color": Color.BG_2,
  "input-primary-border-color-error": Color.ALERT,
  "input-primary-bg-error": Color.TRETIARY_DEFAULT_2,
  "input-primary-box-shadow-color-error": Color.TRETIARY_DEFAULT_2,

  "checkbox-bg-checked": Color.PRIMARY_BA_4,
  "checkbox-bg-hovered": Color.PRIMARY_BA_4,
  "checkbox-box-shadow-focused": Color.PRIMARY_BA_1,
  "checkbox-bg-active": Color.PRIMARY_BA_4,
  "checkbox-border-color-active": Color.PRIMARY_BA_4,
  "checkbox-box-shadow-active": Color.PRIMARY_BA_4,
  "checkbox-bg-disabled": Color.BG_1,

  "input-radio-bg-checked": Color.PRIMARY_BA_4,
  "input-radio-bg-hovered": Color.PRIMARY_BA_4,
  "input-radio-box-shadow-focused": Color.PRIMARY_BA_1,
  "input-radio-bg-focused": Color.PRIMARY_BA_1,
  "input-radio-border-color-focused": Color.PRIMARY_BA_1,

  "switch-bg": Color.BG_2,
  "switch-border-color": Color.BG_2,
  "switch-bg-checked": Color.PRIMARY_BA_5,
  "switch-border-color-checked": Color.PRIMARY_BA_5,

  "tooltip-bg": Color.SECONDARY_BA_3,
  "tooltip-color": Color.WHITE,

  "status-failure": Color.ALERT,
  "status-failure-bg": Color.ALERT_LIGHT,
  "status-success": Color.SUCCESS,
  "status-success-bg": Color.SUCCESS_LIGHT,
  "status-warning": "#ffc700",
  "status-warning-bg": "rgba(255, 199, 0, .12)",
  "status-info": "#70b6f6",
  "status-info-bg": "rgba(112, 182, 246, .12)",
  "status-neutral": Color.BG_5,
  "status-neutral-bg": Color.BG_1,

  "promo-silver": Color.PROMO_SILVER,
  "promo-gold": Color.PROMO_GOLD,
  "promo-asphalt": Color.PROMO_ASPHALT,
  "promo-tomato": Color.PROMO_TOMATO,
  "promo-copper": Color.PROMO_COPPER,
  "promo-mint": Color.PROMO_MINT,
  "promo-sky": Color.PROMO_SKY,
  "promo-neon": Color.PROMO_NEON,
};
