import Color from "../color";

export default {
  "palette-black": Color.BLACK,
  "palette-white": Color.WHITE,
  "palette-bg-1": Color.BG_1,
  "palette-bg-2": Color.BG_2,
  "palette-bg-3": Color.BG_3,
  "palette-bg-4": Color.BG_4,
  "palette-bg-5": Color.BG_5,
  "palette-brand-default-1": Color.BRAND_DEFAULT_1,
  "palette-brand-default-2": Color.BRAND_DEFAULT_2,
  "palette-brand-default-3": Color.BRAND_DEFAULT_3,
  "palette-primary-1": Color.PRIMARY_1,
  "palette-primary-2": Color.PRIMARY_2,
  "palette-primary-3": Color.PRIMARY_3,
  "palette-primary-4": Color.PRIMARY_4,
  "palette-primary-5": Color.PRIMARY_5,
  "palette-tretiary-1": Color.TRETIARY_1,
  "palette-tretiary-2": Color.TRETIARY_2,
  "palette-tretiary-3": Color.TRETIARY_3,
  "palette-tretiary-4": Color.TRETIARY_4,
  "palette-tretiary-5": Color.TRETIARY_5,
  "palette-alert": Color.ALERT,

  "typography-alert": Color.ALERT,
  "typography-success": Color.SUCCESS,
  "typography-secondary": Color.BG_3,

  "button-border-radius": "26px",
  "button-primary-color": Color.WHITE,
  "button-primary-background-color": Color.PRIMARY_4,
  "button-primary-border-color": Color.PRIMARY_4,
  "button-primary-color-hovered": Color.WHITE,
  "button-primary-background-color-hovered": Color.PRIMARY_5,
  "button-primary-border-color-hovered": Color.PRIMARY_5,
  "button-primary-color-active": Color.WHITE,
  "button-primary-background-color-active": Color.PRIMARY_5,
  "button-primary-border-color-active": Color.PRIMARY_5,
  "button-primary-color-disabled": Color.PRIMARY_2,
  "button-primary-background-color-disabled": Color.PRIMARY_1,
  "button-primary-border-color-disabled": Color.PRIMARY_1,

  "button-secondary-color": Color.WHITE,
  "button-secondary-background-color": Color.SECONDARY_4,
  "button-secondary-border-color": Color.SECONDARY_4,
  "button-secondary-color-hovered": Color.WHITE,
  "button-secondary-background-color-hovered": Color.SECONDARY_5,
  "button-secondary-border-color-hovered": Color.SECONDARY_5,
  "button-secondary-color-active": Color.WHITE,
  "button-secondary-background-color-active": Color.SECONDARY_5,
  "button-secondary-border-color-active": Color.SECONDARY_5,
  "button-secondary-color-disabled": Color.SECONDARY_2,
  "button-secondary-background-color-disabled": Color.SECONDARY_1,
  "button-secondary-border-color-disabled": Color.SECONDARY_1,

  "button-pseudo-color": Color.TRETIARY_5,
  "button-pseudo-background-color": Color.WHITE,
  "button-pseudo-border-color": Color.WHITE,
  "button-pseudo-color-hovered": Color.TRETIARY_5,
  "button-pseudo-background-color-hovered": Color.TRETIARY_2,
  "button-pseudo-border-color-hovered": Color.TRETIARY_2,
  "button-pseudo-color-active": Color.TRETIARY_5,
  "button-pseudo-background-color-active": Color.TRETIARY_2,
  "button-pseudo-border-color-active": Color.TRETIARY_2,
  "button-pseudo-color-disabled": Color.SECONDARY_2,
  "button-pseudo-background-color-disabled": Color.SECONDARY_1,
  "button-pseudo-border-color-disabled": Color.SECONDARY_1,

  "button-clear-color": Color.PRIMARY_4,
  "button-clear-color-hovered": Color.PRIMARY_5,
  "button-clear-color-active": Color.PRIMARY_5,

  "input-primary-border-color": Color.BG_3,

  "checkbox-primary-background-color-checked": Color.PRIMARY_4,
  "checkbox-primary-background-color-hovered": Color.PRIMARY_4,
  "checkbox-primary-box-shadow-focused": Color.PRIMARY_1,
  "checkbox-primary-background-color-active": Color.PRIMARY_4,
  "checkbox-primary-border-color-active": Color.PRIMARY_4,
  "checkbox-primary-box-shadow-active": Color.PRIMARY_4,
  "checkbox-primary-background-color-disabled": Color.PRIMARY_1,

  "switch-primary-background-color": Color.BG_2,
  "switch-primary-border-color": Color.BG_2,
  "switch-primary-background-color-checked": Color.PRIMARY_5,
  "switch-primary-border-color-checked": Color.PRIMARY_5,
};
